### ISSUE TITLE
Cannot run please help

### ISSUE THREAD

**Issue by MeAgain55** [faisalthaheem/open-lpr#22]
Hi all.

I am brand new at docker and I am having problems even running most of the components.

Here is what I get when running docker logs xxxxxxxx

[Containers_log.odt](https://github.com/faisalthaheem/open-lpr/files/8061248/Containers_log.odt)

Any help will be greatly appreciated.

Thanks in advance

**Comment by faisalthaheem** [comment]
Hi.
I have pushed new code, can you please review the quick start instructions to see if that helps? Feel free to post followup questions here if any issues.
Thanks

**Comment by faisalthaheem** [comment]
Hi there, I'm sorry for respond late on this, there was an error on the image tag which I have corrected. You should be able to pull the images now and run.
Correction made was to replace this `faisalthaheem/simanno:scripts-2.0` with `faisalthaheem/simanno-scripts:main`

**Comment by MeAgain55** [comment]
Faisal,

I cannot begin of being more grateful of your time.
Your response is  as fast as anyone could hope for.

Many thanks for the software and even more for your support.

I will try the solution you posted and let You know.

Many many thanks again
