### ISSUE TITLE
Not able to install open-lpr on Ubuntu 20.04

### ISSUE THREAD

**Issue by iwansofana** [faisalthaheem/open-lpr#25]
Hi faisalthaheem,

I am not able to install open-lpr docker on Ubuntu 20.04.
It looks like docker missing some files/directories.
What is the minimum requirenment to install open-lpr?

------------------
$ sudo docker-compose up -d

WARNING: The PWD variable is not set. Defaulting to a blank string.
Removing open-lpr_nodered_1
open-lpr_mongodb_1 is up-to-date
open-lpr_redis_1 is up-to-date
open-lpr_broker_1 is up-to-date
Creating open-lpr_ftp_1 ... 
Creating open-lpr_platedetector_1          ... error
Creating open-lpr_ocr_1           ... 
Creating open-lpr_ftp_1                    ... error
Creating open-lpr_rest_1                   ... 

ERROR: for open-lpr_platedetector_1  Cannot create container for service platedetector: failed to mount local volume: mount /filestorage:/var/lib/docker/volumes/open-lpr_shared/_data, flags: 0x1000: no such file or directory

ERROR: for open-lpr_ftp_1  Cannot create container for service ftp: failed to mount local volume: mount /filestorage:/var/lib/docker/vCreating open-lpr_rest_1                   ... error
Creating open-lpr_ocr_1                    ... error
.....
.....
.....
ERROR: for nodered  Cannot start service nodered: error while mounting volume '/var/lib/docker/volumes/open-lpr_shared/_data': failed to mount local volume: mount /filestorage:/var/lib/docker/volumes/open-lpr_shared/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by faisalthaheem** [comment]
Hi there, sorry it took me a while to respond. Please use bash to issue the commands.
